author: "Tobe O <thosakwe@gmail.com>"
description: "Prototypal inheritance for Dart."
homepage: "https://github.com/thosakwe/prototype.git"
name: "prototype"
version: "1.0.0"
dependencies: 
  matcher: "^0.12.0+2"
dev_dependencies: 
  test: "^0.12.17+3"
